# Generated by Django 6.0.3 on 2026-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
