# Generated by Django 6.0.3 on 2026-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
