# Generated by Django 6.0.3 on 2026-05-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classroom_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='student_ids',
            new_name='students',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='schedule_day',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='schedule_time',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='api.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentprofile')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
