# Generated by Django 6.0.3 on 2026-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_childprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='schedule_day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='schedule_time',
            field=models.TimeField(),
        ),
    ]
