# Generated by Django 6.0.3 on 2026-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_classroom_schedule_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('RO', 'Română'), ('ENG', 'Engleză'), ('RO/En', 'Română/Engleză')], default='RO'),
        ),
    ]
