# Generated by Django 6.0.3 on 2026-05-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_student_ids_classroom_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.teacherprofile'),
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.parentprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classroom', to='api.childprofile'),
        ),
    ]
