# Generated by Django 6.0.3 on 2026-05-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_student_ids_classroom_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
