# Generated by Django 6.0.3 on 2026-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_classroom_classroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='skipped_by',
            field=models.ManyToManyField(blank=True, related_name='skipped_lessons', to='api.childprofile'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('RO', 'Română'), ('ENG', 'Engleză'), ('RO/EN', 'Română/Engleză')], default='RO'),
        ),
    ]
