# Generated by Django 6.0.3 on 2026-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson_skipped_by_alter_classroom_classroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='whiteboard_uuid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
