# Generated by Django 6.0.3 on 2026-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lesson_whiteboard_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='whiteboard_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
