# Generated by Django 6.0.3 on 2026-05-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lesson_generated_test_testattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_test_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_answer', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.childprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.lesson')),
            ],
        ),
    ]
