# Generated by Django 6.0.3 on 2026-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_lesson_is_test_active_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='skipped_by',
        ),
        migrations.AddField(
            model_name='lesson',
            name='present_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='attended_lessons', to='api.childprofile'),
        ),
        migrations.DeleteModel(
            name='LessonAttendance',
        ),
    ]
