# Generated by Django 6.0.3 on 2026-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_lesson_skipped_by_lesson_present_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='skipped_by',
            field=models.ManyToManyField(blank=True, related_name='skipped_lessons', to='api.childprofile'),
        ),
    ]
