# Generated by Django 6.0.3 on 2026-05-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lesson_skipped_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'TestResult', 'verbose_name_plural': 'Test Results'},
        ),
    ]
