# Generated by Django 6.0.3 on 2026-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_testresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_material_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
