# Generated by Django 6.0.3 on 2026-05-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_teacheravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_makeup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='makeup_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='individual_makeup_lessons', to='api.childprofile'),
        ),
    ]
