# Generated by Django 6.0.3 on 2026-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_lesson_is_makeup_lesson_makeup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
